FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY src/ /app/

RUN dotnet restore /app/Api/Api.csproj
RUN dotnet publish /app/Api/Api.csproj --no-restore -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine

RUN apk add --no-cache bash

COPY scripts/init_container.sh /bin/
RUN chmod 755 /bin/init_container.sh

WORKDIR /app
COPY --from=build-env /app/out/ .

EXPOSE 80

# LABEL org.opencontainers.image.source https://github.com/andrebarsotti/generic-config-sample-api

ENTRYPOINT ["/bin/init_container.sh"]
