name: ci-action

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: dotnet build

      - name: Tests
        run: |
          dotnet test tests/ApiTests/ApiTests.csproj --no-build
          dotnet test tests/Domain/DomainTests.csproj --no-build
