name: ci-action-pr

on: 
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - 'main'
      - 'release/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dotnet tool packages
        run: |
          dotnet tool restore

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"andrebarsotti_generic-config-sample-api" /o:"andrebarsotti" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build
          dotnet test tests/ApiTests/ApiTests.csproj --no-build
          dotnet test tests/Domain/DomainTests.csproj --no-build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"