name: cd-action

on:
  push:
    # branches:
    #   - 'main'
    #   - 'release/**'

# permissions:
#   contents: read
#   pull-requests: read
#   packages: read/write

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: DockerFile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}