name: ci-action-pr

on: [push]
  # push:
  #   branches:
  #     - 'main'
  #     - 'release/**'
  # pull_request:
  #   types:
  #     - opened
  #     - edited
  #     - reopened
  #   branches:
  #     - 'main'
  #     - 'release/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build and test
        run: |
          dotnet build
          dotnet test tests/ApiTests/ApiTests.csproj --no-build
          dotnet test tests/Domain/DomainTests.csproj --no-build