name: cd-action

on:
  push:
    # branches:
    #   - 'main'
    #   - 'release/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04

    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
  
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Print metada
        run: |
          echo "${{ steps.meta.outputs.tags }}\n\n${{ steps.meta.outputs.labels }}\n\n"
